### ISSUE TITLE
General information

### ISSUE THREAD

**Issue by action5** [coranos/neo-java#3]
Hi, @coranos !
I'm really interested in what is this project going to be (didn't find any info): is it like independent neo node based on Java with UI (like neo-gui) or what?
And what is approximate date of public release?
Thanks! :)

**Comment by coranos** [comment]
It'll be like neo-gui with neo-cli's RPC.

No public release date currently. So probably at least Q3 2018. I havn't written the VM yet, and  there's a lot of testing that needs to be done.
